#!/bin/sh
set -e

#. /usr/share/debconf/confmodule

CONDUWUIT_CONFIG_PATH=/etc/conduwuit
CONDUWUIT_DATABASE_PATH=/var/lib/conduwuit
CONDUWUIT_DATABASE_PATH_SYMLINK=/var/lib/matrix-conduit

case $1 in
  purge)
    # Remove debconf changes from the db
    db_purge

    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -d "$CONDUWUIT_CONFIG_PATH" ]; then
      rm -v -r "$CONDUWUIT_CONFIG_PATH"
    fi

    if [ -d "$CONDUWUIT_DATABASE_PATH" ]; then
      rm -v -r "$CONDUWUIT_DATABASE_PATH"
    fi

    if [ -d "$CONDUWUIT_DATABASE_PATH_SYMLINK" ]; then
      rm -v -r "$CONDUWUIT_DATABASE_PATH_SYMLINK"
    fi
    ;;
esac

#DEBHELPER#
